
job:
  name: StreamComputing
  sources:
    - id: source
      type: kafka
      topic: word-input
      bootstrap-servers: KafkaConfig.IP_PORT
      parallelism: 1
      next: map
  operators:
    - id: map
      type: map
      function: "toLowerCase"
      parallelism: 2
      next: keyby
    - id: keyby
      type: keyby
      key-selector: "word"
      parallelism: 2
      next: reduce
    - id: reduce
      type: reduce
      function: "sum"
      parallelism: 2
      next: sink
  sinks:
    - id: sink
      type: file
      path: "output.txt"
      parallelism: 1